"""Send modal: conversation history (JSONL -> turns -> blocks, budget, bridge fallback)."""

import json
from pathlib import Path

import pytest

from herdr_slackbot import blocks as B
from herdr_slackbot.claude_session import Turn, conversation, conversation_from_lines, cwd_slug
from test_bridge import SHORT, env  # noqa: F401 (env fixture)

FIXTURE = Path(__file__).parent / "fixtures" / "claude_session.jsonl"
SESSION = "abcdef12-0000-4000-8000-000000000001"
CWD = "D:\\main"


def _ts(n):
    return f"2026-10-01T00:{n // 60:02d}:{n % 60:02d}.000Z"


def user(content, n, **extra):
    return {"type": "user", "timestamp": _ts(n), "message": {"role": "user", "content": content}, **extra}


def assistant(msg_id, blocks, stop, n, **extra):
    return {"type": "assistant", "timestamp": _ts(n),
            "message": {"id": msg_id, "role": "assistant", "stop_reason": stop, "content": blocks}, **extra}


def text(t):
    return {"type": "text", "text": t}


def tool_use(i):
    return {"type": "tool_use", "id": f"tu{i}", "name": "Read", "input": {}}


def tool_result(i):
    return {"type": "tool_result", "tool_use_id": f"tu{i}", "content": "file body"}


SYNTHETIC = [
    {"type": "summary", "summary": "x"},
    user([text("Fix the bug"), text("<system-reminder>be careful</system-reminder>")], 1),
    assistant("m1", [{"type": "thinking", "thinking": "hmm"}], "tool_use", 2),
    assistant("m1", [text("Let me look.")], "tool_use", 2),
    assistant("m1", [tool_use(1)], "tool_use", 3),
    user([tool_result(1)], 4),
    user("subagent prompt", 5, isSidechain=True),
    assistant("s1", [text("subagent answer")], "end_turn", 6, isSidechain=True),
    user("<system-reminder>file changed</system-reminder>", 6),  # reminder-only: not a new turn
    assistant("m2", [{"type": "thinking", "thinking": "ok"}], "end_turn", 7),
    assistant("m2", [text("Fixed it in **a.py**.")], "end_turn", 7),
    {"type": "system", "subtype": "turn_duration", "durationMs": 6000},
    user("Caveat: the messages below were generated by local commands", 8, isMeta=True),
    user("<command-name>/model</command-name>", 9),
    user("<local-command-stdout>Set model to opus</local-command-stdout>", 10),
    user([{"type": "image", "source": {"type": "base64", "data": "AAAA"}}, text("What is this?")], 11),
    assistant("m3", [tool_use(2)], "tool_use", 12),
    user([tool_result(2)], 13),
    user([text("[Request interrupted by user for tool use]")], 14),
    user("Try again", 15),
    assistant("m4", [text("Done.")], "end_turn", 16),
    user("And now?", 17),
    assistant("m5", [text("Working on")], None, 18),  # still streaming: not an answer yet
]


def _lines(entries):
    return [json.dumps(e) for e in entries]


def _write_session(tmp_path, entries, session=SESSION, cwd=CWD):
    path = tmp_path / "projects" / cwd_slug(cwd) / f"{session}.jsonl"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(_lines(entries)) + "\n", encoding="utf-8")
    return path


# --- JSONL -> turns ---------------------------------------------------------------------------

def test_conversation_from_synthetic_lines():
    turns = conversation_from_lines(_lines(SYNTHETIC))
    assert [(t.role, t.text) for t in turns] == [
        ("user", "Fix the bug"),
        ("assistant", "Fixed it in **a.py**."),
        ("user", "[image]\n\nWhat is this?"),  # interrupted: no answer
        ("user", "Try again"),
        ("assistant", "Done."),
        ("user", "And now?"),  # unfinished latest answer is left out
    ]
    assert turns[0].at < turns[1].at < turns[2].at


def test_conversation_from_the_real_fixture():
    turns = conversation_from_lines(FIXTURE.read_text(encoding="utf-8").splitlines())
    roles = "".join("u" if t.role == "user" else "a" for t in turns)
    assert roles == "uauauuaua"  # turn 3 was interrupted: no answer
    assert turns[1].text == "2+2 equals 4." and turns[3].text.startswith("# Summary")
    assert turns[-1].text.startswith("The docs directory contains a single mar")


def test_conversation_skips_garbage_and_a_partial_first_line():
    lines = ['"partial tail start', *_lines(SYNTHETIC[1:]), "{not json"]
    assert [t.text for t in conversation_from_lines(lines)][:2] == ["Fix the bug", "Fixed it in **a.py**."]
    assert conversation_from_lines([]) == []


def test_conversation_reads_the_session_file_and_marks_a_cut_tail(tmp_path):
    path = _write_session(tmp_path, SYNTHETIC)
    conv = conversation(SESSION, CWD, base=tmp_path / "projects")
    assert conv is not None and not conv.truncated and len(conv.turns) == 6
    cut = conversation(SESSION, CWD, base=tmp_path / "projects", max_bytes=path.stat().st_size - 50)
    assert cut is not None and cut.truncated
    assert conversation("abcdef12-missing", CWD, base=tmp_path / "projects") is None


# --- turns -> blocks --------------------------------------------------------------------------

def _texts(blocks):
    out = []
    for b in blocks:
        if b["type"] == "section":
            out.append(b["text"]["text"])
        else:
            out.extend(e["text"] for e in b["elements"])
    return out


def test_conversation_blocks_order_labels_and_ids():
    now = 1_000_000.0
    turns = [Turn("user", "hi & <b>", now - 300), Turn("assistant", "# Hello\n**there**", now - 30)]
    blocks = B.conversation_blocks(turns, "coder", now)
    assert _texts(blocks) == ["👤 You · 5 min ago", "hi &amp; &lt;b&gt;", "🤖 coder · just now", "*Hello*\n*there*"]
    assert [b["block_id"] for b in blocks] == ["preview_0", "preview_1", "preview_2", "preview_3"]


def test_conversation_blocks_budget_with_many_turns():
    turns = [Turn("user" if i % 2 == 0 else "assistant", f"message {i} " + "x" * 300, 1000.0 + i)
             for i in range(200)]
    blocks = B.conversation_blocks(turns, "coder", 5000.0)
    assert len(blocks) <= B.PREVIEW_MAX_BLOCKS
    texts = _texts(blocks)
    assert texts[0].startswith("_… ") and "earlier messages not shown" in texts[0]
    hidden = int(texts[0].split()[1])
    assert hidden + (len(blocks) - 1) // 2 == 200
    assert texts[-1].startswith("message 199 ")  # newest message right above the Prompt input
    bodies = [b["text"]["text"] for b in blocks if b["type"] == "section"]
    assert sum(map(len, bodies)) <= B.PREVIEW_MAX_TOTAL_CHARS
    assert len({b["block_id"] for b in blocks}) == len(blocks)


def test_conversation_blocks_char_budget_and_huge_messages():
    big_answer = "start of answer\n" + "\n".join(f"line {i} " + "<&>" * 40 for i in range(2000)) + "\nTHE END"
    big_prompt = "PROMPT HEAD\n" + "y" * 20000
    turns = [Turn("user", "old", 1.0), Turn("assistant", "old answer", 2.0),
             Turn("user", big_prompt, 3.0), Turn("assistant", big_answer, 4.0)] * 4
    blocks = B.conversation_blocks(turns, "coder", 10.0)
    sections = [b["text"]["text"] for b in blocks if b["type"] == "section"]
    assert all(len(s) <= B.SECTION_MAX for s in sections)
    assert sum(map(len, sections)) <= B.PREVIEW_MAX_TOTAL_CHARS
    assert sections[-1].startswith(B.PREVIEW_CUT_MARK) and sections[-1].endswith("THE END")  # tail kept
    prompt = sections[-2]
    assert prompt.startswith("PROMPT HEAD") and prompt.endswith(B.PREVIEW_HEAD_CUT_MARK)  # head kept
    assert "earlier messages not shown" in _texts(blocks)[0]


def test_conversation_blocks_one_huge_answer_alone_fits():
    turns = [Turn("assistant", "```\n" + "code\n" * 5000 + "```\nok", 1.0)]
    (head, body) = B.conversation_blocks(turns, "coder", 2.0)
    text = body["text"]["text"]
    assert len(text) <= B.SECTION_MAX and text.count("```") % 2 == 0 and text.endswith("ok")


def test_conversation_blocks_note_and_omitted_marks():
    turns = [Turn("user", "go", 1.0)]
    blocks = B.conversation_blocks(turns, "coder", 2.0, omitted=True, note=B.PREVIEW_WORKING)
    texts = _texts(blocks)
    assert texts[0] == f"_{B.PREVIEW_OMITTED}_" and texts[-1] == f"_{B.PREVIEW_WORKING}_"
    many = [Turn("user", "m" * 400, float(i)) for i in range(100)]
    blocks = B.conversation_blocks(many, "c", 200.0, omitted=True, note=B.PREVIEW_BLOCKED)
    assert len(blocks) <= B.PREVIEW_MAX_BLOCKS and "+ earlier messages not shown" in _texts(blocks)[0]
    assert _texts(B.conversation_blocks([], "c", 1.0)) == [f"_{B.PREVIEW_EMPTY}_"]


def test_send_view_with_a_full_conversation_stays_within_slack_limits():
    agents = [{"pane_id": "w1:p1", "name": "coder", "agent_status": "idle", "workspace_id": "w1"}]
    turns = [Turn("user" if i % 2 == 0 else "assistant", "z" * 5000, float(i)) for i in range(300)]
    view = B.send_view(agents, {}, "coder", preview=B.conversation_blocks(turns, "coder", 400.0), prompt="p")
    blocks = view["blocks"]
    assert len(blocks) <= 100 and blocks[0]["block_id"] == B.BLOCK_TARGET and blocks[-1]["block_id"] == B.BLOCK_PROMPT
    ids = [b.get("block_id") for b in blocks]
    assert len(set(ids)) == len(ids)
    assert len(json.dumps(view)) < 30000


def test_conversation_mrkdwn_is_verbatim():
    blocks = B.conversation_blocks([Turn("user", "@here", 1.0), Turn("assistant", "@channel", 2.0)], "c", 3.0)
    objs = [b["text"] for b in blocks if b["type"] == "section"] + [e for b in blocks for e in b.get("elements", [])]
    assert objs and all(o.get("verbatim") is True for o in objs)


# --- bridge -----------------------------------------------------------------------------------

def _preview(view):
    return [b for b in view["blocks"] if str(b.get("block_id", "")).startswith("preview")]


def test_send_modal_shows_the_claude_conversation(env):
    _write_session(env.bridge.claude_projects.parent, SYNTHETIC)
    env.herdr.add_agent("w1:p1", "idle", name="coder", session=SESSION, cwd=CWD)
    env.bridge.open_send_modal("TRIG", None, "coder")
    preview = _preview(env.transport.views_updated[-1]["view"])
    texts = _texts(preview)
    assert texts[0].startswith("👤 You") and texts[1] == "Fix the bug"
    assert "🤖 coder" in texts[2] and texts[3] == "Fixed it in *a.py*."
    assert texts[-1] == "And now?" and all(b["block_id"].startswith(B.BLOCK_PREVIEW_PREFIX) for b in preview)


@pytest.mark.parametrize("status,note", [("working", B.PREVIEW_WORKING), ("blocked", B.PREVIEW_BLOCKED)])
def test_busy_claude_agent_shows_history_and_a_note(env, status, note):
    _write_session(env.bridge.claude_projects.parent, SYNTHETIC)
    agent = env.herdr.add_agent("w1:p1", status, name="coder", session=SESSION, cwd=CWD)
    texts = _texts(env.bridge.preview_blocks(agent))
    assert "Fix the bug" in texts and texts[-1] == f"_{note}_"


def test_codex_and_missing_session_fall_back_to_the_last_response(env):
    env.herdr.screens["w1:p1"] = "• codex finished the job\n"
    codex = env.herdr.add_agent("w1:p1", "idle", name="cx", kind="codex")
    assert [b["block_id"] for b in env.bridge.preview_blocks(codex)] == [B.BLOCK_PREVIEW_HEAD, B.BLOCK_PREVIEW_BODY]
    env.herdr.screens["w1:p2"] = SHORT
    claude = env.herdr.add_agent("w1:p2", "idle", name="cl", session="abcdef12-nofile", cwd=CWD)
    blocks = env.bridge.preview_blocks(claude)
    assert blocks[0]["block_id"] == B.BLOCK_PREVIEW_HEAD and "Last response" in blocks[0]["elements"][0]["text"]
    busy = env.herdr.add_agent("w1:p3", "working", name="b", session="abcdef12-nofile2", cwd=CWD)
    assert _texts(env.bridge.preview_blocks(busy)) == [f"_{B.PREVIEW_BUSY}_"]


def test_empty_or_broken_transcript_falls_back(env, monkeypatch):
    _write_session(env.bridge.claude_projects.parent, [{"type": "summary"}])  # no turns
    env.herdr.screens["w1:p1"] = SHORT
    agent = env.herdr.add_agent("w1:p1", "idle", name="coder", session=SESSION, cwd=CWD)
    assert env.bridge.preview_blocks(agent)[0]["block_id"] == B.BLOCK_PREVIEW_HEAD

    def broken(*a, **k):
        raise RuntimeError("disk")
    import herdr_slackbot.bridge as bridge_mod
    monkeypatch.setattr(bridge_mod, "claude_conversation", broken)
    assert env.bridge.preview_blocks(agent)[0]["block_id"] == B.BLOCK_PREVIEW_HEAD
