"""Send modal: conversation history (JSONL -> turns -> blocks, budget, bridge fallback)."""

import json
from pathlib import Path

import pytest

from herdr_slackbot import blocks as B
from herdr_slackbot.claude_session import Turn, conversation, conversation_from_lines, cwd_slug
from test_bridge import SHORT, env  # noqa: F401 (env fixture)

FIXTURE = Path(__file__).parent / "fixtures" / "claude_session.jsonl"
SESSION = "abcdef12-0000-4000-8000-000000000001"
CWD = "D:\\main"


def _ts(n):
    return f"2026-10-01T00:{n // 60:02d}:{n % 60:02d}.000Z"


def user(content, n, **extra):
    return {"type": "user", "timestamp": _ts(n), "message": {"role": "user", "content": content}, **extra}


def assistant(msg_id, blocks, stop, n, **extra):
    return {"type": "assistant", "timestamp": _ts(n),
            "message": {"id": msg_id, "role": "assistant", "stop_reason": stop, "content": blocks}, **extra}


def text(t):
    return {"type": "text", "text": t}


def tool_use(i):
    return {"type": "tool_use", "id": f"tu{i}", "name": "Read", "input": {}}


def tool_result(i):
    return {"type": "tool_result", "tool_use_id": f"tu{i}", "content": "file body"}


SYNTHETIC = [
    {"type": "summary", "summary": "x"},
    user([text("Fix the bug"), text("<system-reminder>be careful</system-reminder>")], 1),
    assistant("m1", [{"type": "thinking", "thinking": "hmm"}], "tool_use", 2),
    assistant("m1", [text("Let me look.")], "tool_use", 2),
    assistant("m1", [tool_use(1)], "tool_use", 3),
    user([tool_result(1)], 4),
    user("subagent prompt", 5, isSidechain=True),
    assistant("s1", [text("subagent answer")], "end_turn", 6, isSidechain=True),
    user("<system-reminder>file changed</system-reminder>", 6),  # reminder-only: not a new turn
    assistant("m2", [{"type": "thinking", "thinking": "ok"}], "end_turn", 7),
    assistant("m2", [text("Fixed it in **a.py**.")], "end_turn", 7),
    {"type": "system", "subtype": "turn_duration", "durationMs": 6000},
    user("Caveat: the messages below were generated by local commands", 8, isMeta=True),
    user("<command-name>/model</command-name>", 9),
    user("<local-command-stdout>Set model to opus</local-command-stdout>", 10),
    user([{"type": "image", "source": {"type": "base64", "data": "AAAA"}}, text("What is this?")], 11),
    assistant("m3", [tool_use(2)], "tool_use", 12),
    user([tool_result(2)], 13),
    user([text("[Request interrupted by user for tool use]")], 14),
    user("Try again", 15),
    assistant("m4", [text("Done.")], "end_turn", 16),
    user("And now?", 17),
    assistant("m5", [text("Working on")], None, 18),  # still streaming: not an answer yet
]


def _lines(entries):
    return [json.dumps(e) for e in entries]


def _write_session(tmp_path, entries, session=SESSION, cwd=CWD):
    path = tmp_path / "projects" / cwd_slug(cwd) / f"{session}.jsonl"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(_lines(entries)) + "\n", encoding="utf-8")
    return path


# --- JSONL -> turns ---------------------------------------------------------------------------

def test_conversation_from_synthetic_lines():
    turns = conversation_from_lines(_lines(SYNTHETIC))
    assert [(t.role, t.text) for t in turns] == [
        ("user", "Fix the bug"),
        ("assistant", "Fixed it in **a.py**."),
        ("user", "[image]\n\nWhat is this?"),  # interrupted: no answer
        ("user", "Try again"),
        ("assistant", "Done."),
        ("user", "And now?"),  # unfinished latest answer is left out
    ]
    assert turns[0].at < turns[1].at < turns[2].at


def test_conversation_from_the_real_fixture():
    turns = conversation_from_lines(FIXTURE.read_text(encoding="utf-8").splitlines())
    roles = "".join("u" if t.role == "user" else "a" for t in turns)
    assert roles == "uauauuaua"  # turn 3 was interrupted: no answer
    assert turns[1].text == "2+2 equals 4." and turns[3].text.startswith("# Summary")
    assert turns[-1].text.startswith("The docs directory contains a single mar")


def test_conversation_skips_garbage_and_a_partial_first_line():
    lines = ['"partial tail start', *_lines(SYNTHETIC[1:]), "{not json"]
    assert [t.text for t in conversation_from_lines(lines)][:2] == ["Fix the bug", "Fixed it in **a.py**."]
    assert conversation_from_lines([]) == []


def test_conversation_reads_the_session_file_and_marks_a_cut_tail(tmp_path):
    path = _write_session(tmp_path, SYNTHETIC)
    conv = conversation(SESSION, CWD, base=tmp_path / "projects")
    assert conv is not None and not conv.truncated and len(conv.turns) == 6
    cut = conversation(SESSION, CWD, base=tmp_path / "projects", max_bytes=path.stat().st_size - 50)
    assert cut is not None and cut.truncated
    assert conversation("abcdef12-missing", CWD, base=tmp_path / "projects") is None


# --- turns -> blocks --------------------------------------------------------------------------

def _texts(blocks):
    out = []
    for b in blocks:
        if b["type"] == "section":
            out.append(b["text"]["text"])
        else:
            out.extend(e["text"] for e in b["elements"])
    return out


def test_conversation_blocks_order_labels_and_ids():
    now = 1_000_000.0
    turns = [Turn("user", "hi & <b>", now - 300), Turn("assistant", "# Hello\n**there**", now - 30)]
    blocks = B.conversation_blocks(turns, "coder", now)
    assert _texts(blocks) == ["👤 You · 5 min ago", "hi &amp; &lt;b&gt;", "🤖 coder · just now", "*Hello*\n*there*"]
    assert [b["block_id"] for b in blocks] == ["preview_0", "preview_1", "preview_2", "preview_3"]


def test_conversation_blocks_budget_with_many_turns():
    turns = [Turn("user" if i % 2 == 0 else "assistant", f"message {i} " + "x" * 300, 1000.0 + i)
             for i in range(200)]
    blocks = B.conversation_blocks(turns, "coder", 5000.0)
    assert len(blocks) <= B.PREVIEW_MAX_BLOCKS
    texts = _texts(blocks)
    assert texts[0].startswith("_… ") and "earlier messages not shown" in texts[0]
    hidden = int(texts[0].split()[1])
    assert hidden + (len(blocks) - 1) // 2 == 200
    assert texts[-1].startswith("message 199 ")  # newest message right above the Prompt input
    bodies = [b["text"]["text"] for b in blocks if b["type"] == "section"]
    assert sum(map(len, bodies)) <= B.PREVIEW_MAX_TOTAL_CHARS
    assert len({b["block_id"] for b in blocks}) == len(blocks)


def test_conversation_blocks_char_budget_and_huge_messages():
    big_answer = "start of answer\n" + "\n".join(f"line {i} " + "<&>" * 40 for i in range(2000)) + "\nTHE END"
    big_prompt = "PROMPT HEAD\n" + "y" * 20000
    turns = [Turn("user", "old", 1.0), Turn("assistant", "old answer", 2.0),
             Turn("user", big_prompt, 3.0), Turn("assistant", big_answer, 4.0)] * 4
    blocks = B.conversation_blocks(turns, "coder", 10.0)
    sections = [b["text"]["text"] for b in blocks if b["type"] == "section"]
    assert all(len(s) <= B.SECTION_MAX for s in sections)
    assert sum(map(len, sections)) <= B.PREVIEW_MAX_TOTAL_CHARS
    assert sections[-1].startswith(B.PREVIEW_CUT_MARK) and sections[-1].endswith("THE END")  # tail kept
    prompt = sections[-2]
    assert prompt.startswith("PROMPT HEAD") and prompt.endswith(B.PREVIEW_HEAD_CUT_MARK)  # head kept
    assert "earlier messages not shown" in _texts(blocks)[0]


def test_conversation_blocks_one_huge_answer_alone_fits():
    turns = [Turn("assistant", "```\n" + "code\n" * 5000 + "```\nok", 1.0)]
    (head, body) = B.conversation_blocks(turns, "coder", 2.0)
    text = body["text"]["text"]
    assert len(text) <= B.SECTION_MAX and text.count("```") % 2 == 0 and text.endswith("ok")


def test_conversation_blocks_note_and_omitted_marks():
    turns = [Turn("user", "go", 1.0)]
    blocks = B.conversation_blocks(turns, "coder", 2.0, omitted=True, note=B.PREVIEW_WORKING)
    texts = _texts(blocks)
    assert texts[0] == f"_{B.PREVIEW_OMITTED}_" and texts[-1] == f"_{B.PREVIEW_WORKING}_"
    many = [Turn("user", "m" * 400, float(i)) for i in range(100)]
    blocks = B.conversation_blocks(many, "c", 200.0, omitted=True, note=B.PREVIEW_BLOCKED)
    assert len(blocks) <= B.PREVIEW_MAX_BLOCKS and "+ earlier messages not shown" in _texts(blocks)[0]
    assert _texts(B.conversation_blocks([], "c", 1.0)) == [f"_{B.PREVIEW_EMPTY}_"]


def test_send_view_with_a_full_conversation_stays_within_slack_limits():
    agents = [{"pane_id": "w1:p1", "name": "coder", "agent_status": "idle", "workspace_id": "w1"}]
    turns = [Turn("user" if i % 2 == 0 else "assistant", "z" * 5000, float(i)) for i in range(300)]
    view = B.send_view(agents, {}, "coder", preview=B.conversation_blocks(turns, "coder", 400.0), prompt="p")
    blocks = view["blocks"]
    assert len(blocks) <= 100 and blocks[0]["block_id"] == B.BLOCK_TARGET and blocks[-1]["block_id"] == B.BLOCK_PROMPT
    ids = [b.get("block_id") for b in blocks]
    assert len(set(ids)) == len(ids)
    assert len(json.dumps(view)) < 30000


def test_conversation_mrkdwn_is_verbatim():
    blocks = B.conversation_blocks([Turn("user", "@here", 1.0), Turn("assistant", "@channel", 2.0)], "c", 3.0)
    objs = [b["text"] for b in blocks if b["type"] == "section"] + [e for b in blocks for e in b.get("elements", [])]
    assert objs and all(o.get("verbatim") is True for o in objs)


# --- bridge -----------------------------------------------------------------------------------

def _preview(view):
    return [b for b in view["blocks"] if str(b.get("block_id", "")).startswith("preview")]


def test_send_modal_shows_the_claude_conversation(env):
    _write_session(env.bridge.claude_projects.parent, SYNTHETIC)
    env.herdr.add_agent("w1:p1", "idle", name="coder", session=SESSION, cwd=CWD)
    env.bridge.open_send_modal("TRIG", None, "coder")
    preview = _preview(env.transport.views_updated[-1]["view"])
    texts = _texts(preview)
    assert texts[0].startswith("👤 You") and texts[1] == "Fix the bug"
    assert "🤖 coder" in texts[2] and texts[3] == "Fixed it in *a.py*."
    assert texts[-1] == "And now?" and all(b["block_id"].startswith(B.BLOCK_PREVIEW_PREFIX) for b in preview)


@pytest.mark.parametrize("status,note", [("working", B.PREVIEW_WORKING), ("blocked", B.PREVIEW_BLOCKED)])
def test_busy_claude_agent_shows_history_and_a_note(env, status, note):
    _write_session(env.bridge.claude_projects.parent, SYNTHETIC)
    agent = env.herdr.add_agent("w1:p1", status, name="coder", session=SESSION, cwd=CWD)
    texts = _texts(env.bridge.preview_blocks(agent))
    assert "Fix the bug" in texts and texts[-1] == f"_{note}_"


def test_codex_and_missing_session_fall_back_to_the_last_response(env):
    env.herdr.screens["w1:p1"] = "• codex finished the job\n"
    codex = env.herdr.add_agent("w1:p1", "idle", name="cx", kind="codex")
    assert [b["block_id"] for b in env.bridge.preview_blocks(codex)] == [B.BLOCK_PREVIEW_HEAD, B.BLOCK_PREVIEW_BODY]
    env.herdr.screens["w1:p2"] = SHORT
    claude = env.herdr.add_agent("w1:p2", "idle", name="cl", session="abcdef12-nofile", cwd=CWD)
    blocks = env.bridge.preview_blocks(claude)
    assert blocks[0]["block_id"] == B.BLOCK_PREVIEW_HEAD and "Last response" in blocks[0]["elements"][0]["text"]
    busy = env.herdr.add_agent("w1:p3", "working", name="b", session="abcdef12-nofile2", cwd=CWD)
    assert _texts(env.bridge.preview_blocks(busy)) == [f"_{B.PREVIEW_BUSY}_"]


def test_empty_or_broken_transcript_falls_back(env, monkeypatch):
    _write_session(env.bridge.claude_projects.parent, [{"type": "summary"}])  # no turns
    env.herdr.screens["w1:p1"] = SHORT
    agent = env.herdr.add_agent("w1:p1", "idle", name="coder", session=SESSION, cwd=CWD)
    assert env.bridge.preview_blocks(agent)[0]["block_id"] == B.BLOCK_PREVIEW_HEAD

    def broken(*a, **k):
        raise RuntimeError("disk")
    import herdr_slackbot.bridge as bridge_mod
    monkeypatch.setattr(bridge_mod, "claude_conversation", broken)
    assert env.bridge.preview_blocks(agent)[0]["block_id"] == B.BLOCK_PREVIEW_HEAD


# --- review fixes (docs/review/history-en.md) ---------------------------------------------------

def queued(prompt, n, mode="prompt", **extra):
    return {"type": "attachment", "timestamp": _ts(n),
            "attachment": {"type": "queued_command", "commandMode": mode, "prompt": prompt, **extra}}


def _pairs(entries, **kw):
    return [(t.role, t.text) for t in conversation_from_lines(_lines(entries), **kw)]


def test_h1_prompt_queued_while_working_starts_its_own_sub_turn():
    entries = [user("first question", 1), assistant("m1", [tool_use(1)], "tool_use", 2), user([tool_result(1)], 3),
               queued("also do Y", 4), assistant("m2", [text("did X and Y")], "end_turn", 5)]
    assert _pairs(entries) == [("user", "first question"), ("user", "also do Y"), ("assistant", "did X and Y")]


def test_h1_interrupt_before_a_queued_prompt_only_drops_that_sub_turn():
    entries = [user("run the tests", 1), assistant("m1", [tool_use(1)], "tool_use", 2), user([tool_result(1)], 3),
               user([text("[Request interrupted by user]")], 4), queued("revert the migration instead", 5),
               assistant("m2", [text("Reverted it.")], "end_turn", 6)]
    assert _pairs(entries) == [("user", "run the tests"), ("user", "revert the migration instead"),
                               ("assistant", "Reverted it.")]


def test_h1_queued_block_prompt_other_modes_and_duplicates():
    blocks = [{"type": "image", "source": {}}, text("this one")]
    entries = [user("q", 1), assistant("m0", [text("a")], "end_turn", 2),
               queued("notification text", 3, mode="task-notification"),  # not a prompt
               queued(blocks, 4), assistant("m1", [text("seen")], "end_turn", 5)]
    assert _pairs(entries) == [("user", "q"), ("assistant", "a"), ("user", "[image]\n\nthis one"),
                               ("assistant", "seen")]
    dup = [user("q", 1), assistant("m1", [tool_use(1)], "tool_use", 2), queued("again", 3, source_uuid="u-src"),
           assistant("m2", [text("first")], "end_turn", 4),
           user("again", 5, uuid="u-src"), assistant("m3", [text("second")], "end_turn", 6)]
    assert _pairs(dup) == [("user", "q"), ("user", "again"), ("assistant", "first"), ("assistant", "second")]


TASK_NOTE = ("<task-notification>\n<task-id>b1</task-id>\n<status>completed</status>\n"
             "<summary>Background command 'build' completed</summary>\n</task-notification>")


def test_h2_task_notification_is_an_event_not_a_prompt():
    entries = [user("start the build in the background", 1), assistant("m1", [text("Started.")], "end_turn", 2),
               user(TASK_NOTE, 3, origin={"kind": "task-notification"}, promptSource="system"),
               assistant("m2", [text("The build passed.")], "end_turn", 4)]
    assert _pairs(entries) == [("user", "start the build in the background"), ("assistant", "Started."),
                               ("event", "Background task finished: Background command 'build' completed"),
                               ("assistant", "The build passed.")]
    older = [user("go", 1), assistant("m1", [text("ok")], "end_turn", 2),
             user("<task-notification>x</task-notification>", 3)]
    assert _pairs(older)[-1] == ("event", "Background task finished")  # tag fallback, no summary
    system = [user("go", 1), user("injected", 2, promptSource="system")]
    assert _pairs(system)[-1] == ("event", "System message")


def test_h2_event_renders_as_one_line_without_raw_tags():
    turns = conversation_from_lines(_lines([user(TASK_NOTE, 3, origin={"kind": "task-notification"}),
                                            assistant("m2", [text("The build passed.")], "end_turn", 4)]))
    blocks = B.conversation_blocks(turns, "coder", 1_790_000_000.0)
    texts = _texts(blocks)
    assert texts[0].startswith("⚙️ _Background task finished: Background command 'build' completed_")
    assert not any("You" in t or "task-id" in t or "&lt;" in t for t in texts)
    assert blocks[0]["type"] == "context" and texts[-1] == "The build passed."


def test_h2_events_count_one_block_in_the_budget():
    turns = [Turn("event", "Background task finished", float(i)) for i in range(100)]
    blocks = B.conversation_blocks(turns, "c", 200.0)
    assert len(blocks) == B.PREVIEW_MAX_BLOCKS and "61 earlier messages not shown" in _texts(blocks)[0]


def test_n1_compact_summary_and_bash_mode_are_not_owner_prompts():
    from herdr_slackbot.claude_session import COMPACT_EVENT
    entries = [user("This session is being continued from a previous conversation. Summary: ...", 1,
                    isCompactSummary=True, isVisibleInTranscriptOnly=True),
               assistant("m1", [text("Continuing.")], "end_turn", 2),
               user("<bash-input>git status</bash-input>", 3),
               user("<bash-stdout>clean</bash-stdout><bash-stderr></bash-stderr>", 4),
               user("thanks", 5), assistant("m2", [text("np")], "end_turn", 6)]
    assert _pairs(entries) == [("event", COMPACT_EVENT), ("assistant", "Continuing."),
                               ("user", "thanks"), ("assistant", "np")]


def test_n2_unclosed_reminder_tag_in_a_prompt_is_kept():
    entries = [user("q1", 1), assistant("m1", [text("a1")], "end_turn", 2),
               user("<system-reminder> tags: why do they appear?", 3), assistant("m2", [text("a2")], "end_turn", 4),
               user("why does `<system-reminder>` appear?", 5), assistant("m3", [text("a3")], "end_turn", 6),
               user([text("real"), text("<system-reminder>note</system-reminder>")], 7),
               user("<system-reminder>only a note</system-reminder>", 8),  # injected: not a new turn
               assistant("m4", [text("a4")], "end_turn", 9)]
    assert _pairs(entries) == [("user", "q1"), ("assistant", "a1"),
                               ("user", "<system-reminder> tags: why do they appear?"), ("assistant", "a2"),
                               ("user", "why does `<system-reminder>` appear?"), ("assistant", "a3"),
                               ("user", "real"), ("assistant", "a4")]


def _linked(entries):
    """Give entries uuids u0.. and a linear parentUuid chain."""
    out, prev = [], None
    for i, e in enumerate(entries):
        e = dict(e, uuid=f"u{i}", parentUuid=prev)
        prev = e["uuid"]
        out.append(e)
    return out


def _rewound():
    # P1 -> A1 -> P2 -> A2 (abandoned), then P2 edited: P2' from A1 -> A2'
    return [user("P1", 1, uuid="p1", parentUuid=None),
            assistant("a1", [text("A1")], "end_turn", 2, uuid="a1", parentUuid="p1"),
            user("P2 old", 3, uuid="p2", parentUuid="a1"),
            assistant("a2", [text("A2 old")], "end_turn", 4, uuid="a2", parentUuid="p2"),
            user("P2 new", 5, uuid="p3", parentUuid="a1"),
            assistant("a3", [text("A2 new")], "end_turn", 6, uuid="a3", parentUuid="p3")]


LIVE = [("user", "P1"), ("assistant", "A1"), ("user", "P2 new"), ("assistant", "A2 new")]
LINEAR = [("user", "P1"), ("assistant", "A1"), ("user", "P2 old"), ("assistant", "A2 old"),
          ("user", "P2 new"), ("assistant", "A2 new")]


def test_n3_abandoned_branch_is_hidden():
    assert _pairs(_rewound()) == LIVE
    compacted = _rewound()[:4] + [  # a compact boundary links through logicalParentUuid
        {"type": "system", "subtype": "compact_boundary", "uuid": "cb", "parentUuid": None, "logicalParentUuid": "a1"},
        user("P2 new", 5, uuid="p3", parentUuid="cb"),
        assistant("a3", [text("A2 new")], "end_turn", 6, uuid="a3", parentUuid="p3")]
    assert _pairs(compacted) == LIVE


def test_n3_untrusted_chain_falls_back_to_linear_order():
    broken = _rewound()
    broken[4] = dict(broken[4], parentUuid="gone")  # parent missing inside a complete file
    assert _pairs(broken) == LINEAR
    assert _pairs(broken, tail_cut=True) == LINEAR  # turns exist before the break
    no_uuid = _rewound()
    del no_uuid[3]["uuid"]
    assert _pairs(no_uuid) == LINEAR
    cycle = _rewound()
    cycle[0] = dict(cycle[0], parentUuid="a3")
    assert _pairs(cycle) == LINEAR


def test_n3_cut_tail_where_the_chain_leaves_before_the_first_turn():
    entries = [assistant("a0", [text("old tail")], "end_turn", 0, uuid="a0", parentUuid="before-tail")] + _rewound()
    entries[1] = dict(entries[1], parentUuid="a0")
    assert _pairs(entries, tail_cut=True) == LIVE
    assert _pairs(entries) == LINEAR  # a complete file: the missing parent is a real break


def test_n3_linked_records_keep_queued_prompts_and_events():
    entries = _linked([user("q", 1), assistant("m1", [tool_use(1)], "tool_use", 2), queued("more", 3),
                       assistant("m2", [text("done")], "end_turn", 4),
                       user(TASK_NOTE, 5, origin={"kind": "task-notification"}),
                       assistant("m3", [text("noted")], "end_turn", 6)])
    assert [r for r, _ in _pairs(entries)] == ["user", "user", "assistant", "event", "assistant"]


def test_n4_english_readme_has_no_korean_ui_text():
    import re
    readme = (Path(__file__).parent.parent / "README.md").read_text(encoding="utf-8")
    hangul = set(re.findall("[가-힣]+", readme))
    assert hangul <= {"한국어"}, hangul  # only the language link


# --- re-check fixes (docs/review/history-en-recheck.md) --------------------------------------------

def test_o2_reminder_plus_command_bookkeeping_is_not_a_prompt():
    entries = [user("q", 1), assistant("m1", [text("a")], "end_turn", 2),
               user("<system-reminder>r</system-reminder><command-name>/foo</command-name>", 3),
               user([text("<system-reminder>r</system-reminder>"), text("<local-command-stdout>x</local-command-stdout>")], 4)]
    assert _pairs(entries) == [("user", "q"), ("assistant", "a")]  # the answer stays with "q"
    kept = [user([text("<system-reminder>r</system-reminder>"), {"type": "image", "source": {}}], 1)]
    assert _pairs(kept) == [("user", "[image]")]


def test_o2_raw_text_fallback_still_strips_reminders():
    from herdr_slackbot.claude_session import _prompt_text
    blocks = [text("<system-reminder>secret note</system-reminder><command-name>/foo</command-name>")]
    assert _prompt_text(blocks) == "<command-name>/foo</command-name>"
    entries = [queued("<system-reminder>secret note</system-reminder><command-name>/foo</command-name>", 1)]
    assert _pairs(entries) == [("user", "<command-name>/foo</command-name>")]


def test_o3_prompts_on_a_separate_root_stay_in_linear_order():
    entries = [user("P1", 1, uuid="p1", parentUuid=None),
               assistant("a1", [text("A1")], "end_turn", 2, uuid="a1", parentUuid="p1"),
               {"type": "attachment", "uuid": "h1", "parentUuid": None, "attachment": {"type": "hook_success"}},
               user("P2", 3, uuid="p2", parentUuid="h1"),
               assistant("a2", [text("A2")], "end_turn", 4, uuid="a2", parentUuid="p2")]
    assert _pairs(entries) == [("user", "P1"), ("assistant", "A1"), ("user", "P2"), ("assistant", "A2")]


def test_o3_only_real_forks_are_hidden():
    # p1 -> a1 -> {p2 -> a2 (fork, hidden), p3 -> a3 (live)}; x1 has a parent outside the tail: kept
    rewound = _rewound()
    entries = rewound[:4] + [user("X", 5, uuid="x1", parentUuid="outside")] + rewound[4:]
    assert [t for _, t in _pairs(entries)] == ["P1", "A1", "X", "P2 new", "A2 new"]
    # deeper fork: the abandoned branch has two prompts below the common ancestor
    deep = _rewound()[:4] + [user("P3 old", 5, uuid="p4", parentUuid="a2"),
                             assistant("a4", [text("A3 old")], "end_turn", 6, uuid="a4", parentUuid="p4"),
                             user("P2 new", 7, uuid="p3", parentUuid="a1"),
                             assistant("a3", [text("A2 new")], "end_turn", 8, uuid="a3", parentUuid="p3")]
    assert _pairs(deep) == LIVE
